// <auto-generated />
using System;
using ConsultasMedicas.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ConsultasMedicas.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230919021820_modelconsulta")]
    partial class modelconsulta
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.11");

            modelBuilder.Entity("ConsultasMedicas.API.Models.ConsultaModel", b =>
                {
                    b.Property<int?>("IdConsulta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataHoraConsulta")
                        .HasColumnType("TEXT");

                    b.Property<int?>("IdMedico")
                        .IsRequired()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("IdPaciente")
                        .IsRequired()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("IdRecepcionista")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MedicoModelIdMedico")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Observacoes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("PacienteModelIdPaciente")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("RecepcionistaModelIdRecepcionista")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TipoConsulta")
                        .HasColumnType("INTEGER");

                    b.HasKey("IdConsulta");

                    b.HasIndex("MedicoModelIdMedico");

                    b.HasIndex("PacienteModelIdPaciente");

                    b.HasIndex("RecepcionistaModelIdRecepcionista");

                    b.ToTable("Consultas");
                });

            modelBuilder.Entity("ConsultasMedicas.API.Models.EspecialidadeModel", b =>
                {
                    b.Property<int?>("IdEspecialidade")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NomeEspecialidade")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.HasKey("IdEspecialidade");

                    b.ToTable("Especialidades");
                });

            modelBuilder.Entity("ConsultasMedicas.API.Models.HorarioModel", b =>
                {
                    b.Property<int>("IdHorario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("HorarioDisponivel")
                        .HasColumnType("TEXT");

                    b.Property<int?>("MedicoIdMedico")
                        .HasColumnType("INTEGER");

                    b.HasKey("IdHorario");

                    b.HasIndex("MedicoIdMedico");

                    b.ToTable("HorarioModel");
                });

            modelBuilder.Entity("ConsultasMedicas.API.Models.MedicoModel", b =>
                {
                    b.Property<int?>("IdMedico")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CRM")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("EspecialidadeIdEspecialidade")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("IdEspecialidade")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.HasKey("IdMedico");

                    b.HasIndex("EspecialidadeIdEspecialidade");

                    b.ToTable("Medicos");
                });

            modelBuilder.Entity("ConsultasMedicas.API.Models.PacienteModel", b =>
                {
                    b.Property<int?>("IdPaciente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CPF")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("HistoricoMedico")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("Sobrenome")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.HasKey("IdPaciente");

                    b.ToTable("Pacientes");
                });

            modelBuilder.Entity("ConsultasMedicas.API.Models.RecepcionistaModel", b =>
                {
                    b.Property<int?>("IdRecepcionista")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CPF")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("NumeroTelefone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Sobrenome")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.HasKey("IdRecepcionista");

                    b.ToTable("Recepcionistas");
                });

            modelBuilder.Entity("ConsultasMedicas.API.Models.ConsultaModel", b =>
                {
                    b.HasOne("ConsultasMedicas.API.Models.MedicoModel", null)
                        .WithMany("Consultas")
                        .HasForeignKey("MedicoModelIdMedico");

                    b.HasOne("ConsultasMedicas.API.Models.PacienteModel", null)
                        .WithMany("Consultas")
                        .HasForeignKey("PacienteModelIdPaciente");

                    b.HasOne("ConsultasMedicas.API.Models.RecepcionistaModel", null)
                        .WithMany("ConsultasAgendadas")
                        .HasForeignKey("RecepcionistaModelIdRecepcionista");
                });

            modelBuilder.Entity("ConsultasMedicas.API.Models.HorarioModel", b =>
                {
                    b.HasOne("ConsultasMedicas.API.Models.MedicoModel", "Medico")
                        .WithMany("HorariosDisponiveis")
                        .HasForeignKey("MedicoIdMedico");

                    b.Navigation("Medico");
                });

            modelBuilder.Entity("ConsultasMedicas.API.Models.MedicoModel", b =>
                {
                    b.HasOne("ConsultasMedicas.API.Models.EspecialidadeModel", "Especialidade")
                        .WithMany("Medicos")
                        .HasForeignKey("EspecialidadeIdEspecialidade");

                    b.Navigation("Especialidade");
                });

            modelBuilder.Entity("ConsultasMedicas.API.Models.EspecialidadeModel", b =>
                {
                    b.Navigation("Medicos");
                });

            modelBuilder.Entity("ConsultasMedicas.API.Models.MedicoModel", b =>
                {
                    b.Navigation("Consultas");

                    b.Navigation("HorariosDisponiveis");
                });

            modelBuilder.Entity("ConsultasMedicas.API.Models.PacienteModel", b =>
                {
                    b.Navigation("Consultas");
                });

            modelBuilder.Entity("ConsultasMedicas.API.Models.RecepcionistaModel", b =>
                {
                    b.Navigation("ConsultasAgendadas");
                });
#pragma warning restore 612, 618
        }
    }
}
